name: Monitor Diario Oficial

on:
  schedule:
    # Roda de hora em hora, das 8h às 18h (Horário aprox. Brasil), Seg-Sex
    - cron: '0 11-21 * * 1-5'
  workflow_dispatch: # Botão para rodar manual

jobs:
  check-and-post:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write # Permissão para commitar o last_processed.txt

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar dependências do Sistema (Poppler)
        run: |
          sudo apt-get update
          sudo apt-get install -y poppler-utils

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar bibliotecas Python
        run: pip install -r requirements.txt

      - name: Executar Bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        run: python main.py

      - name: Salvar Estado (Commit)
        run: |
          git config --global user.name 'DiarioBot'
          git config --global user.email 'bot@noreply.github.com'
          
          if [[ -n $(git status -s last_processed.txt) ]]; then
            git add last_processed.txt
            git commit -m "🤖 Update: Novo diário processado"
            git push
          else
            echo "Nenhuma mudança para commitar."
          fi
